### ISSUE TITLE
Fix paddings of audio/mp3 tag in layout

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/hfg-documentation-generator#13]
cc @PaulRaschke

**Comment by PaulRaschke** [comment]
Hi @b-g,

what exactly is the problem with the paddings?

**Comment by b-g** [comment]
@PaulRaschke Ugly or no paddings: 

<img width="1026" alt="Screen Shot 2019-03-29 at 11 16 46" src="https://user-images.githubusercontent.com/480224/55225992-3562c600-5214-11e9-8a54-3c0abb92554b.png">

(but fixing the OpenMoji website bugs would be more important)
