### ISSUE TITLE
Todos Paul / v4.0 (based on Kirby 3)

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/hfg-documentation-generator#20]
@PaulRaschke as discussed :)

- [x] Fix/tidy up styles landing (overview) page
- [x] Fix layout issues #16 #14 
- [x] Add users feature. Roles Students and Admin (Dozent). Students can just edit the Dokus they created. 
- [x] Evaluate HfG Auth tbd whether we should add it or not
- [x] Evaluate/Upgrade to Kirby v3

**Comment by felixhaeberle** [comment]
I did a experimental kirby v3 port of this project, it can be found here: 
https://github.com/felixhaeberle/hfg-documentation-generator

Doesn't have all the features yet as in v2 and is still buggy because custom tags and plugins need rewrites, but no error mess beside of that.

**Comment by b-g** [comment]
@felixhaeberle Great!! But @PaulRaschke is almost there as well with Kirby v3 and other new features ... could the two of you join forces? :)

**Comment by felixhaeberle** [comment]
@PaulRaschke Feel free to DM! 👍

**Comment by b-g** [comment]
Message via email from @PaulRaschke, moving the conversation to Github to cc @bohnacker. Will respond in the next post. 

der Dokugenerator ist fast fertig, mit den neuen Features, um ihn zentral für Studenten pro Kurs zu hosten und die Authentifizierung über den HfG Mail-Server.
Folgende "Probleme" kann ich aber vermutlich (zeitlich) nicht beheben und ein paar Fragen sind noch offen, daher würde ich um deine Beurteilung bitten:

- Der Staticbuilder ist nicht mit Kirby 3 kompatibel und es scheint auch keine Alternative zu geben
- Studenten können theoretisch auf Dokumentationen anderer Gruppen zugreifen, sofern sie die Panel URL kennen, sehen diese jedoch nicht in ihrer Panel Ansicht aufgelistet
- Das automatische Anpassen der URL an Änderungen des Titels funktioniert nicht mehr, da man keine Panel Redirects mehr definieren kann. Manuell kann man die URL nach wie vor anpassen.

Hier noch die paar Fragen:
- Wie wichtig ist das Überarbeiten der Overview Page?
- Sollen Studenten mehr als eine Dokumentation erstellen können?
- Sollen Professoren auch über den HfG Mail-Server authentifiziert werden, oder einen abgekoppelten Admin Account besitzen? Eine Authentifizierung über den HfG-Mail Account würde voraussichtlich zusätzlich Aufwand generieren

**Comment by b-g** [comment]
@PaulRaschke cc @bohnacker 
> der Dokugenerator ist fast fertig, mit den neuen Features, um ihn zentral für Studenten pro Kurs zu hosten und die Authentifizierung über den HfG Mail-Server.

Super! Vielen lieben Dank dafür!!

> Der Staticbuilder ist nicht mit Kirby 3 kompatibel und es scheint auch keine Alternative zu geben

Dann haben wir keine Wahl ... einfach voresrt rausmachen und wir hoffen dann einfach dass das Plugin über die Zeit auf Kirby 3 nachzieht.

> Studenten können theoretisch auf Dokumentationen anderer Gruppen zugreifen, sofern sie die Panel URL kennen, sehen diese jedoch nicht in ihrer Panel Ansicht aufgelistet

OK. Nicht kritisch innerhalb eines Kurses ... müssen wir halt einfach den Studis sagen.

> Das automatische Anpassen der URL an Änderungen des Titels funktioniert nicht mehr, da man keine Panel Redirects mehr definieren kann. Manuell kann man die URL nach wie vor anpassen.

OK. Finde ich sogar besser.

> Wie wichtig ist das Überarbeiten der Overview Page?

Wichtig. Ist ja praktisch die Visitenkarten für alle Kurse. Falls viel Aufwand Bescheid geben dann müssen wir schauen.

> Sollen Studenten mehr als eine Dokumentation erstellen können?

Ja/Jein. Es gibt immer Fälle das Studenten unter dem Semster die Gruppe wechseln. Es sollte also mindestens Möglich sein dass ein Student Teil von mehreren Dokus ein kann. Besser wäre aber bestimmt einfach zu erlauben das jeder mehrere Dokus anlegen kann und auch beliebig andere in den Credits hinzugügen kann (bzw. auch das editieren teilen kann)

> Sollen Professoren auch über den HfG Mail-Server authentifiziert werden

Lieber per Adminaccount ... es gibt ja keine echte API um zu wissen ob ein User Prof ist.

OK? Wir können sonst auch skypen ... falls schneller. Bin gut zu erreichen. Danke!!

**Comment by b-g** [comment]
Hi @PaulRaschke, Could you please push :) We are all waiting eagerly to give the new documentation generator a go 🚀 / test it 🤞!

**Comment by PaulRaschke** [comment]
Hi @b-g,
pushed it :) Sry, that it took a bit longer than expected, had to fix some bugs and test the functionality. Hopefully everything now works as it should.

**Comment by b-g** [comment]
Hi @PaulRaschke, Super! Can I merge it with master? And could you:

- Tick off the todos in the first post of the issue
- Close #12 
- Update the readme with some important infos / bullet points e.g. first login user is Admin, every user is authenticated against the HfG User Database etc.

**Comment by PaulRaschke** [comment]
Should be ready to be merged with master!

**Comment by b-g** [comment]
Thanks! Merged!
