### ISSUE TITLE
Rearrange course information

### ISSUE THREAD

**Issue by bohnacker** [hfg-gmuend/hfg-documentation-generator#24]
Right now there is a duplication of the department where the course happend (IG; KG; PG; IoT, SG) and of the supervisor information: in the overview fields and in each documentation. Also, each documentation has a semester number that might conflict with information in the overview.

Another potential problem: what happens with courses that are happening in more than one department, e.g. KG/IG. Then there is no way to edit the "Major" field accordingly.

My suggestion: 
In the overview page combine fields "Major" and "Course (as in curriculum)" to something like "Course subtitle".
In each documentation get rid of the fields "Supervisors", "Major" and "Semester".

What do you think @b-g, @PaulRaschke, @benni-t?

**Comment by benni-t** [comment]
I think your suggestion sounds reasonable – I agree with you.

**Comment by PaulRaschke** [comment]
I have already discussed this with @b-g and the consensus was that only the course should be shared between documentations and the overview page.

The problem with documentations for projects in which students from different departments participated could be solved with a [kirby structure field](https://getkirby.com/docs/reference/panel/fields/structure) that would allow to add multiple major and semester combinations. Alternatively, the information could be set in the individual user information and displayed after the name in the list of authors in the documentations introduction (e.g. - firstname lastname IoT6).

But you have a point when you say that the conflicting information can be quite confusing. Therefore, perhaps the overall best solution is to remove the fields from the documentation as you suggested.

What is your opinion @b-g?

**Comment by bohnacker** [comment]
After discussing this also with @b-g we will try the following solution:

All information about the course, department, semester and supervisors will be set in the overview.
To be quite flexible with naming all that there should be the following fields:
- Course Subject (e.g. "Interactive Data Visualization" or "Social Design") as free text
- Course Name as in Curriculum (e.g. "Programmiertes Entwerfen 2") as free text
- Semester and Department long (e.g. "Interaktionsgestaltung 2") as free text
- Semester and Department short (e.g. "IG2") as free text

I also thought of making the last two (Semester and Department) as structure fields or tag fields, but that will get quite complicated for courses with more than one department and/or semester.

In the layout this fields should be used as follows.

On the overview page:
<img width="664" alt="Bildschirmfoto 2020-03-25 um 11 32 01" src="https://user-images.githubusercontent.com/2828139/77527502-84c1ed80-6e8c-11ea-84b9-f341f894e900.png">

In the documentation:
<img width="542" alt="Bildschirmfoto 2020-03-25 um 10 26 07" src="https://user-images.githubusercontent.com/2828139/77527531-960afa00-6e8c-11ea-8479-b67faffaac0c.png">

**Comment by bohnacker** [comment]
After a bit more discussion and thinking that's the "final" solution:

Instead having two free text fields for department(s) and semester(s) there should be one field as a tag list (e.g. IG4, IoT3). For the overview we will implement a logic to make long names from that information.
