### ISSUE TITLE
Course overview view

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/hfg-documentation-generator#9]
This is to have a discussion thread for the currently missing course overview view ...

FYI @phytrisha ... Hartmut @bohnacker worked already a bit on it. Please pull before you start. Thanks.

**Comment by phytrisha** [comment]
@b-g @bohnacker my suggestion for the implementation: 
- students work on their documentations as they do right now
- at the end, they copy the contents of their documentations (contents/1-my-documenation-hfg) in one "project"
- if more than 1 documentation is found in contents, localhost:8000 refers to the overview page where all documentations are displayed (similar to the overview page right now, only minor styling tweaks required imo)

I think this would be the easiest, most straight-forward way. I'll see how I can implement it that way.

Additionally, @Sam0711er and @pfs-15 worked on a pretty cool and easy to use kiosk template ([https://github.com/hfg-gmuend/hfg-exhibition-grid](https://github.com/hfg-gmuend/hfg-exhibition-grid)) and I think it would make sense to keep these two things visually consistent.

**Comment by b-g** [comment]
Hi @phytrisha, 

Many thanks for the thoughts! Yes, this is exactly as we intended it. We simply did not implement it (think of MVP), as we wanted to see first students working with it. Comments: I would not "too" automate 2. and 3. ... would find it better to tell the "owners" of the courses:

1. gather all contents of student documentations in a single folder
2. put in the same folder an `overview.txt` file (or add it via kirby)
3. if kirby finds a `overview.txt` ... localhost:8000 refers to the overview page

RE: hfg-exhibition-grid
Yes I'm very aware of the project, as I initiated it :) But I would currently vote against visually sync both in a 100% consistent style. Happy to sync fonts and small things ... but to do it in a proper way before the Semesterausstellung seems too much effort. OK?

🙏

**Comment by b-g** [comment]
@phytrisha @bohnacker 

after thinking it over ... even easier would be:

1. Gather all contents of student documentations in the folder (`content/`)
2. Use kirby to add an `overview/overview.txt` page into the content folder (`content/overview/overview.txt`)
3. Course owner fills out the details of the overview page
4. Course owner makes overview page visible and moves the overview page to `content/1-overview` ... and as the very first page always refers to localhost:8000 ... the overview is always loaded first. Done.

Almost all the requirements are already available out of the box in Kirby. The only non-standard feature would be, that the Overview page finds every Project page and displays them in a list/grid.

**Comment by phytrisha** [comment]
@b-g Thanks for your feedback! I think the first approach would actually be easier, as @bohnacker already did most of the heavy lifting for that (as seen in screenshot, only some styling needed), but I'll look into what turns out to be easier.

![image](https://user-images.githubusercontent.com/12794995/51799654-0e900f80-2224-11e9-8029-63a4393a95a4.png)

RE: hfg-exhibition-grid
Ah, very cool! Yeah, totally agree, shouldn't put too much effort into it. To me, it's mainly font-family, weight and sizes that make out the large difference in visual style. Aligning that shouldn't be too much effort imo.

**Comment by PaulRaschke** [comment]
Hello @b-g and @phytrisha,
a similiar functionality as @phytrisha suggested is already implemented.
When more than one documentation is visible kirby automatically routes to the overview page when accessing the root url. Here you can see the implementation in code:
https://github.com/hfg-gmuend/hfg-documentation-generator/blob/668cf524232f5b2069409f83d1778324d0f50a6a/site/plugins/routes/routes.php#L5-L16
But feel free to change this if another workflow is desired :)

If I understood @bg correctly it is planned that the overview page should show information about the course, am i right?
Currently the overview page is hidden for editors inside the panel as seen here:
https://github.com/hfg-gmuend/hfg-documentation-generator/blob/668cf524232f5b2069409f83d1778324d0f50a6a/site/roles/editor.php#L14-L16
I would then suggest that the overview should be always editable for students.

**Comment by b-g** [comment]
Hi @PaulRaschke, Great! Many thanks for the code gold nuggets! 🙏

**Comment by b-g** [comment]
Ping @phytrisha :) Would like to upload it for the approval of our external partners in our SG2 course. Could you aim to finish it soonish? :) Possible? Sorry to bother you!

**Comment by b-g** [comment]
Gentle ping for news @phytrisha :) Server (w/ password protection) is online and ready to go. Plz!

**Comment by b-g** [comment]
@phytrisha ok + thx! Will be on the road from 12°° - 4°°pm ... but would really like to send it off this evening.

**Comment by phytrisha** [comment]
@b-g could you add me as contributor? Unable to push to master otherwise

**Comment by b-g** [comment]
@phytrisha Added you.

**Comment by phytrisha** [comment]
@b-g Cool thanks. Updated overview.php and stylesheets are now commited to master, ready to give it a spin :)

**Comment by b-g** [comment]
@phytrisha Thanks + Nope! Tested it with all the contents of SG2 ... getting this:
<img width="1440" alt="screen shot 2019-02-04 at 11 02 28" src="https://user-images.githubusercontent.com/480224/52201666-779f0500-286c-11e9-9c6f-c24d9b9a50d8.png">

Probably: Can you add a check whether there is a valid image (to prevent crashing if something is fishy)?

**Comment by phytrisha** [comment]
@b-g Argh crap. On it.

**Comment by b-g** [comment]
@phytrisha Also ... the cover image is not retina. Please add a srcset ... see how we deal with images in general. Will be off the grid until 4pm now. Sorry!

**Comment by phytrisha** [comment]
@b-g fixed the issue with the missing cover images. images should be displayed in retina now as well. can you check? thanks!

**Comment by b-g** [comment]
@phytrisha Thanks! Yes it is kind of working ... comments:

**technical**
* cover image "img" html element is missing the src attribute, won't work on old browser. Please add.
* srcset is linking multiple time to the same images ... use kirby resize to adjust the image sizes, so that it makes sense in the layout. Here is a snippet from my portfolio:

```php
    <div class="project__item">
      <a href="<?php echo $project->url() ?>">
        <?php
          $cover = $project->cover()->toFile();
          if ($cover) {
            $_size1x = ($project->importance() == 'high') ? 554 : 254;
            $_size2x = $_size1x * 2;
            $_src1x = $cover->resize($_size1x, null, 90);
            $_src2x = $cover->resize($_size2x, null, 85);
            echo html::img($_src1x->url(), array(
              'srcset' => $_src1x->url().' 1x, '.$_src2x->url().' 2x',
              'class'  => "project__item__image"
            ));
          }
        ?>
        <p class="project__item__date"><?php echo $date ?></p>
        <p class="project__item__title"><?php echo $project->title() ?></p>
      </a>
    </div>
```


* Headline of Overview should reflect the course title

**design**
* It looks ugly! :) Can you tweak the layout so that Overview and the rest of the site go well together? Why small images? Why does every student needs its own line? etc.
* Clicking on the images should open up the doku

<img width="1612" alt="screen shot 2019-02-04 at 15 33 20" src="https://user-images.githubusercontent.com/480224/52214952-4685fb00-2893-11e9-9914-c94a96ff38f9.png">

**Comment by phytrisha** [comment]
@b-g thanks for the snippet, saves a lot of time for php-noob me :)
I implemented it in the latest commit, together with the fix for the link covering the image as well (and some basic styling issues, that caused firefox to breakup the grid.

Towards design: okay, I thought this design was sort of set, as it had already been started in the version I started with, but sure, I can iterate another loop there.

The coursetitle is reflected by the .txt file in content (content/overview/overview.txt) as it's part of the content, not the overall template right? So you'd have to fix that in your version.

**Comment by phytrisha** [comment]
oh, and there seems to be an error with the commas in the authors... seems like $auth->count() returns a wrong number in one case...

**Comment by PaulRaschke** [comment]
Hi @phytrisha,
you can also use the kirbytag()-function to get a responsive image element as used in the introduction snippet:
https://github.com/hfg-gmuend/hfg-documentation-generator/blob/eab65db16480bdde6a5fc4bfd80bf4fbed56804b/site/snippets/introduction.php#L49
So the image elements in the overview are generated in the same way as the other images and they are also affected by an update of the image tag or a change of the responsive image setting in the config:
https://github.com/hfg-gmuend/hfg-documentation-generator/blob/eab65db16480bdde6a5fc4bfd80bf4fbed56804b/site/config/config.php#L51

**Comment by b-g** [comment]
@phytrisha 

> oh, and there seems to be an error with the commas in the authors... seems like $auth->count() returns a wrong number in one case...

Sorry can't help on this one at the moment. Maybe @PaulRaschke knows more?

> Towards design: okay, I thought this design was sort of set, as it had already been started in the version I started with, but sure, I can iterate another loop there.

Great! Looking forward :) + Sorry for the confusion, should have mentioned that the commits of Hartmut were not meant as layout suggestions.

**Comment by b-g** [comment]
@phytrisha Many thanks! Looks ok now. Please close the issue if this is the final one. Fine with me. 🙏

<img width="1130" alt="screen shot 2019-02-05 at 16 51 25" src="https://user-images.githubusercontent.com/480224/52285334-6df9c800-2966-11e9-8ac7-c4cd6ee03f5d.png">

**Comment by phytrisha** [comment]
Okay cool. For version 2 we should probably put some actual time in the layout and in the process work on visual alignment with the kiosk app. Perhaps one template for both applications would be best, but we'll see. Cheers!
